name: Build and Push to GHCR

on:
  push:
    branches: [main]  # or your working branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build image
      run: docker build -t ghcr.io/tsooflahav/backend_hearmonitor:latest .

    - name: Push image
      run: docker push ghcr.io/tsooflahav/backend_hearmonitor:latest
