name: Build and deploy Docker app to Azure Web App - meowmeowmeowmeowmeowmeow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build and push Docker image
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'meowmeowmeowmeowmeowmeow'
          images: 'ghcr.io/${{ github.repository }}:${{ github.sha }}'
