name: Build and deploy Docker app to Azure Web App - meowmeowmeowmeowmeowmeow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "dckr_pat_yJt80tmZb_v5h3yPuVctEgjEuvQ" | docker login -u tsooflahav --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t tsooflahav/backend_hearmonitor:${{ github.sha }} .
          docker push tsooflahav/backend_hearmonitor:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CC57923B1C0347898D17A76DEBF19874 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3A7A158E48CA4F719937462FF16D73BB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D9E9AB85A70E48428C5D3EAA90BFE2D6 }}

      - name: 'Deploy Docker to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'meowmeowmeowmeowmeowmeow'
          slot-name: 'Production'
          images: 'tsooflahav/backend_hearmonitor:${{ github.sha }}'


          
